name: uzum
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  build_runner: ^2.4.11
  flutter_svg: ^2.0.10+1
  popover: ^0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/uzum_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: UzumBold
      fonts:
        - asset: assets/fonts/uzum_bold.ttf

    - family: ExtraBold
      fonts:
        - asset: assets/fonts/uzum_extrabold.ttf

    - family: SemiBold
      fonts:
        - asset: assets/fonts/uzum_semi_bold.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/uzum_medium.ttf

    - family: NumberMedium
      fonts:
        - asset: assets/fonts/uzum_medium.ttf


